# Generated by Django 2.0 on 2019-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='kind',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
